version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lucas
      - MONGO_INITDB_ROOT_PASSWORD=970521
    ports:
      - "27017:27017"
    volumes:
      - D:/workspace/MongoDB-Data:/data/db